project:
  type: book
  output-dir: docs

book:
  title: "COURSE NUMBER"
  author: "Norah Jones"
  date: "last-modified"
  date-format: "MMM D, YYYY"
  chapters:
    - index.qmd
    - u1.qmd
    - u2.qmd
    - u3.qmd
    - u4.qmd
    - u5.qmd
    - u6.qmd    
    - assessment.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
  pdf:
    documentclass: scrreprt



